/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TreatmentRouteImport } from './routes/treatment'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SqlAuditRouteImport } from './routes/sql-audit'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as MirofishRouteImport } from './routes/mirofish'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HermesRouteImport } from './routes/hermes'
import { Route as GovernorRouteImport } from './routes/governor'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as CandlesightRouteImport } from './routes/candlesight'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentRoute = TreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlAuditRoute = SqlAuditRouteImport.update({
  id: '/sql-audit',
  path: '/sql-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const MirofishRoute = MirofishRouteImport.update({
  id: '/mirofish',
  path: '/mirofish',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesRoute = HermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernorRoute = GovernorRouteImport.update({
  id: '/governor',
  path: '/governor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CandlesightRoute = CandlesightRouteImport.update({
  id: '/candlesight',
  path: '/candlesight',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/arena': typeof ArenaRoute
  '/brain': typeof BrainRoute
  '/candlesight': typeof CandlesightRoute
  '/chart': typeof ChartRoute
  '/console': typeof ConsoleRoute
  '/governor': typeof GovernorRoute
  '/hermes': typeof HermesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mirofish': typeof MirofishRoute
  '/operator': typeof OperatorRoute
  '/pulse': typeof PulseRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sql-audit': typeof SqlAuditRoute
  '/trades': typeof TradesRoute
  '/treatment': typeof TreatmentRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/arena': typeof ArenaRoute
  '/brain': typeof BrainRoute
  '/candlesight': typeof CandlesightRoute
  '/chart': typeof ChartRoute
  '/console': typeof ConsoleRoute
  '/governor': typeof GovernorRoute
  '/hermes': typeof HermesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mirofish': typeof MirofishRoute
  '/operator': typeof OperatorRoute
  '/pulse': typeof PulseRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sql-audit': typeof SqlAuditRoute
  '/trades': typeof TradesRoute
  '/treatment': typeof TreatmentRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/arena': typeof ArenaRoute
  '/brain': typeof BrainRoute
  '/candlesight': typeof CandlesightRoute
  '/chart': typeof ChartRoute
  '/console': typeof ConsoleRoute
  '/governor': typeof GovernorRoute
  '/hermes': typeof HermesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mirofish': typeof MirofishRoute
  '/operator': typeof OperatorRoute
  '/pulse': typeof PulseRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/sql-audit': typeof SqlAuditRoute
  '/trades': typeof TradesRoute
  '/treatment': typeof TreatmentRoute
  '/universe': typeof UniverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/arena'
    | '/brain'
    | '/candlesight'
    | '/chart'
    | '/console'
    | '/governor'
    | '/hermes'
    | '/login'
    | '/memory'
    | '/mirofish'
    | '/operator'
    | '/pulse'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/sql-audit'
    | '/trades'
    | '/treatment'
    | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/arena'
    | '/brain'
    | '/candlesight'
    | '/chart'
    | '/console'
    | '/governor'
    | '/hermes'
    | '/login'
    | '/memory'
    | '/mirofish'
    | '/operator'
    | '/pulse'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/sql-audit'
    | '/trades'
    | '/treatment'
    | '/universe'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/arena'
    | '/brain'
    | '/candlesight'
    | '/chart'
    | '/console'
    | '/governor'
    | '/hermes'
    | '/login'
    | '/memory'
    | '/mirofish'
    | '/operator'
    | '/pulse'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/sql-audit'
    | '/trades'
    | '/treatment'
    | '/universe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArenaRoute: typeof ArenaRoute
  BrainRoute: typeof BrainRoute
  CandlesightRoute: typeof CandlesightRoute
  ChartRoute: typeof ChartRoute
  ConsoleRoute: typeof ConsoleRoute
  GovernorRoute: typeof GovernorRoute
  HermesRoute: typeof HermesRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  MirofishRoute: typeof MirofishRoute
  OperatorRoute: typeof OperatorRoute
  PulseRoute: typeof PulseRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  SqlAuditRoute: typeof SqlAuditRoute
  TradesRoute: typeof TradesRoute
  TreatmentRoute: typeof TreatmentRoute
  UniverseRoute: typeof UniverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment': {
      id: '/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof TreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-audit': {
      id: '/sql-audit'
      path: '/sql-audit'
      fullPath: '/sql-audit'
      preLoaderRoute: typeof SqlAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirofish': {
      id: '/mirofish'
      path: '/mirofish'
      fullPath: '/mirofish'
      preLoaderRoute: typeof MirofishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes': {
      id: '/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof HermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governor': {
      id: '/governor'
      path: '/governor'
      fullPath: '/governor'
      preLoaderRoute: typeof GovernorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candlesight': {
      id: '/candlesight'
      path: '/candlesight'
      fullPath: '/candlesight'
      preLoaderRoute: typeof CandlesightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArenaRoute: ArenaRoute,
  BrainRoute: BrainRoute,
  CandlesightRoute: CandlesightRoute,
  ChartRoute: ChartRoute,
  ConsoleRoute: ConsoleRoute,
  GovernorRoute: GovernorRoute,
  HermesRoute: HermesRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  MirofishRoute: MirofishRoute,
  OperatorRoute: OperatorRoute,
  PulseRoute: PulseRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  SqlAuditRoute: SqlAuditRoute,
  TradesRoute: TradesRoute,
  TreatmentRoute: TreatmentRoute,
  UniverseRoute: UniverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
